"""init

Revision ID: 5e322210a0c4
Revises: 
Create Date: 2025-09-19 18:31:35.721742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e322210a0c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('jockeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jockeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jockeys_name'), ['name'], unique=False)

    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex_enum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horses_name'), ['name'], unique=False)

    op.create_table('entries',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('jockey_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('place IS NULL OR place > 0', name='ck_place_positive'),
    sa.CheckConstraint('time_ms IS NULL OR time_ms >= 0', name='ck_time_ms_nonnegative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'horse_id', 'jockey_id'),
    sa.UniqueConstraint('event_id', 'horse_id', 'jockey_id', name='uq_entry_event_pair'),
    sa.UniqueConstraint('event_id', 'horse_id', name='uq_entry_event_horse'),
    sa.UniqueConstraint('event_id', 'jockey_id', name='uq_entry_event_jockey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horses_name'))

    op.drop_table('horses')
    op.drop_table('owners')
    with op.batch_alter_table('jockeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jockeys_name'))

    op.drop_table('jockeys')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_starts_at'))

    op.drop_table('events')
    # ### end Alembic commands ###
